### PR TITLE
Allow status -v to display start and end times.

### PR DESCRIPTION
**Pull request by rquadling**
Currently, the timestamp shown by ``phinx status`` relates to the creation of the migration. If you want to know when the migration was actually run, you have to jump into the DB.

With this PR, ``phinx status -v`` will show the Started and Finished times from the phinxlog.

### CODE REVIEW

**Comment by robmorgan** [comment]
I'll take this as soon as I'm back from holidays. 

Cheers,

Rob

**Comment by robmorgan** [comment]
I've decided rather than add all these extra methods and verbosity bloat, it might be better to just add the start and end times by default

**Comment by shadowhand** [comment]
@robmorgan what's the status on adding start and end times?

Thank you for contributing! The branch you made this PR against is no longer accepting patches. This probably happened because we didn't merge your changes fast enough. :sob:

Please create a new PR against the current default branch if you want to see these changes merged.

**Comment by rquadling** [comment]
I'll be rebasing on the 4th or 5th of Jan.

**Pull request closed without merging**
