### PR TITLE
PostgreSQL - improve geography types creation

### PR DESCRIPTION
**Pull request by mdouchin**
Added some code to create geography fields like this

```
geography(geometry, 4326)
geography(POLYGON, 4326)
```

Any comments welcome

### CODE REVIEW

**Comment by mdouchin** [comment]
Please tell me if this kind of change is ok for rollback and column changes. This PR adds the geometry type constraint Polygon|Linestring|Point .

**Comment by mdouchin** [comment]
Any comment on this close please, to help me understand and propose more suitable contribution next time ?

**Comment by robmorgan** [comment]
hi @mdouchin I closed the 0.5.x-dev branch and it closed a lot of open PRs. I'm reopening them for consideration against the 0.7 branch which is now `master`. Happy to accept your contribution, thanks!

**Comment by mdouchin** [comment]
Ok thanks !

**Pull request merged**
