### PR TITLE
Allow console input to be used within adapters

### PR DESCRIPTION
**Pull request by bgetsug**
I created a custom adapter that needed to access the (symfony) console options, and I needed to make this change to make that possible.

### CODE REVIEW

**Comment by robmorgan** [comment]
@bgetsug I'm changing it to be merged with `0.6.x-dev`.

**Comment by robmorgan** [comment]
@bgetsug does this PR actually add any methods to the adapter classes?

**Comment by bgetsug** [comment]
@robmorgan I did not add any new methods to existing adapter classes. It's just that the instance of `InputInterface` was never making it to any adapter when setup in `Environment::getAdapter()`.

**Comment by robmorgan** [comment]
@bgetsug right I see, thanks! 👍

**Pull request merged**
