### PR TITLE
Add arguments for timestamps columns names.

### PR DESCRIPTION
**Pull request by samizdam**
Implement #576 && #706

### CODE REVIEW

**Comment by samizdam** [comment]
I don't sure, but this feature will be applied only after phar rebuilding? 
Do I must push with pull request binary file? 
Contributing FAQ not provide some info about it...

**Comment by shadowhand** [comment]
@samizdam please add tests.

**Comment by samizdam** [comment]
@shadowhand  this method is already covered. 
I'm update my branch with upstream now. 

table-coverage

**Comment by robmorgan** [comment]
I dont really think we need this feature. If people want to change types etc or column names I generally tell them just to use `addColumn()` instead. I'd rather leave this method simple like Rails.

**Comment by shadowhand** [comment]
I don't see any problem with having defaults that can be modified rather than hard coded. Seems like a reasonable approach to me.

**Comment by rquadling** [comment]
I've implemented this feature, along with appropriate guarding of null (you cannot have a column called null - who'd have thought that!) and unit tests.

**Pull request closed without merging**
