### PR TITLE
Add support for BLOB sizes in MySQL (issue #45)

### PR DESCRIPTION
**Pull request by mamchenkov**
This pull requests adds support for:

* TINYBLOB
* MEDIUMBLOB
* LONGBLOB

Mostly, using copy paste of the existing TEXT field sizes.

### CODE REVIEW

**Comment by dereuromark** [comment]
Nice! :+1: 

Refs https://github.com/robmorgan/phinx/issues/45 ( and https://github.com/robmorgan/phinx/pull/469 ).

**Comment by lorenzo** [comment]
Nice! :+1:

**Comment by burzum** [comment]
:+1:

**Comment by jadb** [comment]
:+1:

**Comment by dakota** [comment]
:+1:

**Comment by jadb** [comment]
:+1:

**Comment by dereuromark** [comment]
Well, its nice (congrats!) that you are now a rich guy ( https://twitter.com/_rjm_/status/596625381379186688 ), but it would be even nicer if you would take of your current responsibility as the main manager of this repo :)

A few major frameworks and libs (like CakePHP for example) use it as a direct dependency and therefore require useful features and bugfixes to be merged in a reasonable timeframe.
If you cannot spare time, now you at least have the money to buy a few helpers.
But I am sure here in github are also quite a few very competent people you could ask to co-admin this repo and continue to support it in your name.

Any feedback or plans regarding maintaining this repo on your end would be much appreciated.

if you need any help, please don't hesitate to ask us folk. We don't bite (usually).

**Comment by bravo-kernel** [comment]
:+1:

**Comment by josegonzalez** [comment]
Hey @robmorgan, any chance you have a few seconds to take a look at this PR? I took a look into it this weekend and seems to work as desired. I use phinx at my dayjob (@seatgeek) and this would solve a few hacks for us :)

**Comment by robmorgan** [comment]
thanks everyone, sorry for the delays! project updates coming soon.

**Comment by robmorgan** [comment]
@dereuromark thank you for revising your comment.

**Comment by jadb** [comment]
:+1: @dereuromark!

**Comment by dereuromark** [comment]
Thanks for continuing your work.

**Comment by flangofas** [comment]
:+1:

**Pull request merged**
