### PR TITLE
Select from multiple migration paths for creation

### LINKED ISSUE #833: Cannot create migrations with paths using glob patterns
Given a `migrations` path with a glob pattern new migrations will be created in a directory literally named after the pattern. Thus:

```
paths:
  migrations: foo/*/migrations
```

Executing `phinx create FooBar` will create a new migration in the path `foo/*/migrations/20160503134337_foo_bar.php` literally.

Not sure how to tackle this properly but maybe ask the user where to put the migration if a glob pattern is used?

### PR DESCRIPTION
**Pull request by mbrodala**
This asks the user where to create migrations if multiple
valid migration paths where found.

Fixes #833

### CODE REVIEW

**Comment by mbrodala** [comment]
@robmorgan Any specific reason why this wasn't accepted?

**Comment by robmorgan** [comment]
@mbrodala I closed the `0.5.x-dev` branch and it closed a lot of open PRs. I'm reopening them for consideration against the `0.7` branch which is now `master`.

**Comment by mbrodala** [comment]
OK, I'll rebase.

**Comment by mbrodala** [comment]
Hm, seems like this was already added with 28d9afb, thus there's nothing to do here anymore. :-)

**Comment by robmorgan** [comment]
@mbrodala ahh funny that ;)

**Pull request closed without merging**
