### PR TITLE
Config File Location Feature

### PR DESCRIPTION
**Pull request by ralphschindler**
Features added:
- ability to provide PHINX_CONFIG_DIR to scan
- ability to traverse one level deep looking for matching config

Thoughts on including this?

The motivation is to allow the config files to live outside of root, but also in a discoverable place.  The idea behind the environment variable is so that isolated development environments (virtual, docker compose), can specify the migration directory (should be be more than 1 level deep).

### CODE REVIEW

**Comment by rquadling** [comment]
OOI, if PHINX_CONFIG_DIR is specificed, why look beyond that directory? If the file is further down, just set the PHINX_CONFIG_DIR appropriately?

For this to be accepted, we'll need the documentation updated as well as appropriate unit tests.
And rebased to the current dev branch (0.6.x-dev).

**Comment by ralphschindler** [comment]
I can and will provide those things, wanted to start a discussion first to see if the concept/prototype would be well received.

I agree on stopping at the environment provided directory and not scanning cwd. I'll make that change.

Thanks for having a look.

**Comment by ralphschindler** [comment]
tests added, docs added, base changed for PR. please review.

**Comment by ralphschindler** [comment]
@rquadling bump :)

**Comment by ralphschindler** [comment]
@robmorgan ping

**Comment by rquadling** [comment]
Please rebase to 0.7.x

**Comment by ralphschindler** [comment]
I just tried to rebase to 0.7.x-dev, unfortunately, the branch even without my commits doesn't run tests correctly.  There is another PR here that will fix the `getMock()` warnings.  Also, the phpunit.xml.dist file should likely disable integration tests by default (ie: skip things that actually need a database present).

Do you have a timeline for getting 0.7.0 released? I would like to coordinate getting it in shape, and getting my PR working against that branch.  Thanks!

**Comment by robmorgan** [comment]
@ralphschindler I will merge with the existing `0.6.x-dev` branch a do a mini-release with this change and a few others.

**Comment by robmorgan** [comment]
@ralphschindler I've having a problem running this change locally directly from master. It seems its loading the `phinx.php` application stub in `app/phinx.php` by mistake. Can you reproduce this locally?

1. Clone `master`
2. Run `php bin/phinx status`

```
[RuntimeException]                                                      
  PHP file '/Users/robbym/Code/phinx/app/phinx.php' must return an array
```

Unit tests pass though. I changed them slightly to work on Windows.

**Comment by ralphschindler** [comment]
I don't fully understand what this workflow represents.  Is it a valid use case to clone the project and host migrations inside it? Running `php bin/phinx` seems to imply that you're treating the phinx project itself as the project hosting the migrations (is this valid?)

Finding `app/phinx.php` and expecting it to be a phinx configuration file seems to be the right behavior, no?  After all, the traditional use case would be running phinx from `vendor/bin/phinx` (in which phinx would never look inside vendor/ for a matching config file.)

Please advise.

(Alternatively, if you rename app/phinx.php to something like app/console.php, this would alleviate the immediate problem.)

(Additionally, this enhancement was included b/c the original source code had a @todo in it, just not 10 levels deep: https://github.com/robmorgan/phinx/pull/869/files#diff-c9eb06ef069427530fa3f9f516d6bbd0L190)

**Comment by robmorgan** [comment]
@ralphschindler its how most of us actually do Phinx development.

Yeah I'll have to consider if we rename the class. Originally for some crazy idea I can't remember I thought about traversing up, but deeper obviously makes much more sense.

Can you also help me to fix the tests on Windows? I managed to get 2/3 working, see latest build for an example: https://ci.appveyor.com/project/robmorgan/phinx/build/1.0.1515

I'm going to revert this PR whilst we make the changes so I can ship a mini-release.

**Comment by ralphschindler** [comment]
Do you have a channel you chat in about dev stuffs?

**Comment by rquadling** [comment]
@ralphschindler We have now merged all branches into master, so can you rebase onto master please.

**Pull request merged**
