### PR TITLE
Allow aliases for the template creation class names.

### PR DESCRIPTION
**Pull request by rquadling**
We have a set of migration template creation classes that are namespaced. Allowing them to be accessed via an alias which is part of our Phinx setup simplifies things for our developers.

One thing I wasn't sure about is making ```Config::getAlias()``` part of ```ConfigInterface```.

If I did, any pre-existing class implementing that interface will now require an empty function, assuming they didn't want to use any aliases.

So, hopefully, just where it is is OK.

### CODE REVIEW

**Comment by RQuadling** [comment]
Is there anything to be done about AppVeyor failing?

**Comment by rquadling** [comment]
Any chance this could be merged please?

**Comment by rquadling** [comment]
Thank you.

**Comment by robmorgan** [comment]
:+1:

**Pull request merged**
