### PR TITLE
Documentation improvements for valid column types

### PR DESCRIPTION
**Pull request by mamchenkov**
* Added ```uuid``` to the list of columns
* Added ```jsonb``` to Postgres
* Sorted column types alphabetically

### CODE REVIEW

**Comment by w2pc** [comment]
IMO uuid should not be added to the list here as that is not universal.
It's already noted that uuid is available for the Postgres adapter

On Fri, Jul 24, 2015 at 5:00 AM, Leonid Mamchenkov <notifications@github.com

**Comment by mamchenkov** [comment]
@w2pc to me it looks like the documentation is misleading, since it says that only Postgres supports UUID.  We are using UUID just fine with MySQL and SQL Server.  I took a quick look around and it seems that SQLite adapter supports it too (which makes it 4 out of 4).  PDO adapter, which all other ones are extending, supports it.  And the phinx type constant is defined in AdapterInterface, which all adapters implement.

To me it looks pretty universal.

**Comment by w2pc** [comment]
But a UUID in MySQL is a column type of 16byte "binary" which is already in
the column types.

On Fri, Jul 24, 2015 at 6:34 AM, Leonid Mamchenkov <notifications@github.com

**Comment by mamchenkov** [comment]
@w2pc not all databases support UUID natively.  Those that don't, are using ```char(36)```.  The adapters are mapping this difference pretty nice, so that from the point of view of migrations, you don't even need to know if the engine supports uuid column type.

Currently, the documentation suggests that uuid column type is only supported by Postgres, so you probably should (implicitly) check the database engine in your migration and use ```char(36)``` for everything that is not Postgres.  Which is not the case.

Just trying help people keep migrations simple and abstract. :)

**Comment by mamchenkov** [comment]
Just checked to be sure, and MysqlAdapter uses ```char(36)``` for UUID:

* [Line 814](https://github.com/robmorgan/phinx/blob/master/src%2FPhinx%2FDb%2FAdapter%2FMysqlAdapter.php#L814)
* [Line 871](https://github.com/robmorgan/phinx/blob/master/src%2FPhinx%2FDb%2FAdapter%2FMysqlAdapter.php#L871)

**Pull request merged**
