### PR TITLE
Add bootstrap file handling

### PR DESCRIPTION
**Pull request by enygma**
This PR is related to functionality mentioned in Issue #549 about executing a bootstrap file when any command is called.

### CODE REVIEW

**Comment by MasonM** [comment]
:+1: this would be very handy

**Comment by enygma** [comment]
Any chance of this getting merged? Looks like the Scrutinizer build failed for no good reason...

**Comment by m1ome** [comment]
You can use a config file as a bootstrap file.

**Comment by enygma** [comment]
Um, correct me if I'm wrong but the configuration files are yaml files, not PHP and those don't allow loading or calling out to external scripts.

**Comment by m1ome** [comment]
@enygma, you can use a ".php" file for configuration, here you can do you "bootstrap" thing, please check the [docs](http://docs.phinx.org/en/latest/commands.html#configuration-file-parameter) you can do what you want in this file and then "return" a **Phinx** configuration.

**Comment by robmorgan** [comment]
@enygma please refer to the docs. PHP-based configs are now documented and should work for you.

**Comment by enygma** [comment]
@robmorgan thanks for the update! I'll check into it.

**Pull request closed without merging**
