### PR TITLE
Update PdoAdapter.php

### PR DESCRIPTION
**Pull request by Awnage**
Fix for #243 to make sure more recent versions of MySQL are happy without Travis complaining too much.

### CODE REVIEW

**Comment by Awnage** [comment]
lol, Travis fails on PHP 5.3. GOOD! No one should be using it anyway. =)

**Comment by enygma** [comment]
:+1: on this - it's a definite must for future use of Phinx. Otherwise I think quite a few people will have to find another tool... :(

**Comment by robmorgan** [comment]
@Awnage please make sure those arrays use the 5.3 syntax otherwise the old PHPs will still complain (even if kept in a conditional block)

**Comment by Awnage** [comment]
Look good, or would you prefer a single comprehensive patch.

**Comment by robmorgan** [comment]
no it looks okay, its not perfect PSR, so I'll clean it up a bit.

**Pull request merged**
