### PR TITLE
Fix scope mixing of config and runtime for template source settings.

### PR DESCRIPTION
**Pull request by rquadling**
Defaults for the source of the template (a generator class or a file) can be overwritten by the command line options. In both cases, you cannot define/provide both values.

Also, if you define the class but supply the template on the command line (or vice versa), the command line options take precedence.

### CODE REVIEW

**Comment by rquadling** [comment]
Anything stopping this being merged?

**Comment by rquadling** [comment]
Should I be basing this on v0.4 or v.05?

**Comment by robmorgan** [comment]
0.5.x-dev now please

Cheers,

Rob

**Comment by rquadling** [comment]
OK. I'll close this one once I've got a new PR made.

**Comment by rquadling** [comment]
Hmm. How do I get github to know I want to merge to 0.5.x-dev?

I rebased onto that branch and then a push -f.

**Comment by rquadling** [comment]
Made a new https://github.com/robmorgan/phinx/pull/698. Closing this one.

**Pull request closed without merging**
