### PR TITLE
Feature/breakpoint support

### PR DESCRIPTION
**Pull request by rquadling**
Allow breakpoints to be set to stop accidental rollbacks. When a breakpoint is set, rollback will stop when it reaches that migration. Can be overridden with ``--force``.

### CODE REVIEW

**Comment by shadowhand** [comment]
Can you add a description to this and rebase it please?

**Comment by robmorgan** [comment]
Btw guys I'm not in a rush to merge this feature. If it turns out to be something that a lot of people want I might change my mind. I'd prefer to focus on as few new features as possible and prioritise fixing bugs as we move towards 1.0.

**Comment by rquadling** [comment]
This feature requires the verbose status patch.

**Comment by rquadling** [comment]
Our team is actively using this feature. I'd really like to see it merged. Any feedback would be great.

**Comment by rquadling** [comment]
Closed and replaced with https://github.com/robmorgan/phinx/pull/874

**Pull request merged**
