### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anned20**
Copyright 2015 -> 2016

### CODE REVIEW

**Comment by robmorgan** [comment]
👍

**Comment by rquadling** [comment]
@anned20 , thank you. See you again in 6 months time!? 😁

**Comment by anned20** [comment]
I guess :smile_cat:

**Comment by rquadling** [comment]
I've often wondered about the date in a (C) message. Seems it should be the oldest date!

http://www.legalcorner.net/articletemplate1.asp?name=copyright_art_003
https://www.plagiarismtoday.com/2011/11/08/how-to-write-a-copyright-notice/
http://www.clickandcopyright.com/copyright-resources/copyright-symbol-usage.aspx

I read these and see that the copyright should be from the initial publication date, which is 2012

https://github.com/robmorgan/phinx/commit/38190e029e67af993a48ddb4e2e71c8739b4b634

**Comment by rquadling** [comment]
Also no idea what happens when collaborators and contributors ass their pennies worth.

**Comment by robmorgan** [comment]
@anned20 @rquadling I don't really care too much to be honest... more or less I'd rather take a simple commit from somebody. Even if its a simple typo fix, date etc. That way people learn the whole PR, Github workflow. It's also how I personally got started in open-source ;)

**Pull request merged**
