### PR TITLE
Dependent seeders

### PR DESCRIPTION
**Pull request by antonienko**
Created a way to execute Seeders in order of Dependency.

Now the SeedInterface provides a method getParentSeed. Seeder instances should set their parent property to the name of the Seeder they depend on.

The new object SeedFetcher will take care of returning the seeders in the proper order of execution.

Parent seeders can be dependent on other seeders too. Old seeders should still work without modification.

### CODE REVIEW

**Comment by antonienko** [comment]
Proposal to solve [issue 737](https://github.com/robmorgan/phinx/issues/737)

**Comment by Starojitski** [comment]
I started using phinx yesterday and immediately noticed that there was no way to have custom seeding order without tweaking file/class names. Almost commenced writing a fix but luckily checked opened issues! Are there plans to merge this feature any time soon?

**Comment by oytuntez** [comment]
This is a highly needed fundamental feature, I hope it gets merged soon.

**Comment by rreynier** [comment]
@robmorgan curious why this was closed. Seems like there is decent demand for something like this.

**Comment by rquadling** [comment]
Branch 0.5.x-dev has been deleted.

Please rebase off of master and we can reconsider this PR.

Thank you.

**Comment by oytuntez** [comment]
@rquadling you should have given heads-up to the PRer (@antonienko) instead of holding this for a year :) 0.5.x-dev was quite existing when this PR was submitted. 

Next time, let's say.

**Comment by antonienko** [comment]
@rquadling @oytuntez @rreynier Rebased

**Comment by oytuntez** [comment]
Beautiful, @antonienko, thank you!

**Comment by enygma** [comment]
If this was correctly rebased why was it closed? It was a while back but I don't see a merge associated with it.

**Comment by lorenzo** [comment]
It was github that closed it automatically when the target branch was deleted.

If anyone is willing to re-open it, I'm also willing to review and merge :)

**Comment by enygma** [comment]
@antonienko - see above?

**Comment by lorenzo** [comment]
@enygma what should I look at exactly?

**Comment by antonienko** [comment]
I have tried to create the pull request again. It's been more than 18 months since the pull request was created and it got zero attention from the maintainers of the project.

Some checks are failing, but I don't have more time to dedicate to it, neither the will, so if someone else wants to take it over, I would be glad to transfer ownership of my fork.

https://github.com/cakephp/phinx/pull/1143

**Pull request closed without merging**
