### PR TITLE
Added support for Symfony3

### PR DESCRIPTION
**Pull request by gnugat**
I've locally bumped phinx to use Symfony3 and all the tests pass.
To me it looks like phinx work out of the box with the soon to be released so I propose to make the `composer.json` compatible with it.

### CODE REVIEW

**Comment by voidcontext** [comment]
+1 for this, it would be helpful.

**Comment by gnugat** [comment]
By the way Symfony 3 has been released yesterday :) .

**Comment by robmorgan** [comment]
@gnugat and PHP 7 was tagged. Does Phinx work properly with Symfony 3? I'll need to check it.

**Comment by gnugat** [comment]
I checked it with Symfony 3 beta1 and the tests passed. I can check it again if needed.

**Comment by robmorgan** [comment]
no thats okay.

**Comment by gnugat** [comment]
Brilliant, thanks! Do you know when it's going to be tagged?

**Comment by robmorgan** [comment]
Most likely later this month after we get feedback on the seed feature.

**Comment by gnugat** [comment]
great, thank you.

**Comment by fromYukki** [comment]
Hello guys. When this path will be released?

**Comment by gnugat** [comment]
No idea, but in the meantime it's available with `0.5@dev` (aka `dev-master`).

**Comment by robmorgan** [comment]
which is currently breaking on some PHP versions.

**Pull request merged**
