### PR TITLE
Alternative template options.

### PR DESCRIPTION
**Pull request by RQuadling**

### CODE REVIEW

**Comment by RQuadling** [comment]
Hmm. I rebased (I think - not a git expert) and it seems I got a LOT of extra log entries. The code is working (so far as I can tell) and all the changes are in. Not sure about the log entries showing up though.

**Comment by shadowhand** [comment]
It looks like you merged instead of rebased, which is not ideal. Please run `git rebase 0.4.x-dev`.

**Comment by RQuadling** [comment]
Aha. New branch created in the process.

**Comment by RQuadling** [comment]
A new pull request, https://github.com/robmorgan/phinx/pull/437, replaces this one.

**Comment by shadowhand** [comment]
There's no need to create new pull requests, just replace your existing branch and force push. So long as the branch name matches, the pull request will pick up the changes.

**Comment by RQuadling** [comment]
I use SourceTree and there's no push --force option (as far as I can see). Will use the commandline for this in future. Still learning. Thank you for your patience.

**Pull request closed without merging**
