### PR TITLE
Merge Master

### PR DESCRIPTION
**Pull request by robmorgan**

### CODE REVIEW

**Comment by rquadling** [comment]
With master now being the dev branch (THANK YOU!!!!), I should be able to start re-merging everything back in.

**Comment by rquadling** [comment]
Need to edit https://github.com/robmorgan/phinx/wiki/Releasing-a-new-version-of-Phinx to reflect the new procedure.

**Comment by robmorgan** [comment]
@rquadling 🎉 👍  - it makes it much simpler. I already edited the Wiki this morning.

**Comment by rquadling** [comment]
Is there any reason why we don't merge gh-pages into master:/doc?

**Comment by robmorgan** [comment]
@rquadling I guess at the moment the master:/doc folder is used for `docs.phinx.org` site and `gh-pages` is specially for the main website. I guess it doesn't hurt to keep the marketing site separate as it might not always be hosted on Github pages.

**Comment by rquadling** [comment]
OK.

**Pull request closed without merging**
