### PR TITLE
Adding support for multiple migration paths.

### PR DESCRIPTION
**Pull request by dancryer**
This pull request adds support for multiple migration paths, in what I hope is a Phinx-friendly way. 

Breakdown of changes:
- Changed `Config::getMigrationPath()` to `Config::getMigrationPaths()`
- Added a conversion from string to a single-item array (for older config files)
- Updated migration `Manager` class to support multiple paths, via new method `getMigrationFiles()`
- Updated `CreateCommand` to use Symfony `ChoiceQuestion` to allow the user to select which migration path to use when creating a new migration.
- Updated tests that referenced `getMigrationPath()`
- Added new test that the conversion from string to array for migration path works
- Updated docs

See #232 and #343 for further discussion.

### CODE REVIEW

**Comment by dancryer** [comment]
@robmorgan @shadowhand - I'm not entirely sure why AppVeyor is failing on this PR, but please do let me know if I need to change anything. :)

**Comment by dancryer** [comment]
It seems that @arnaudroulee and I have both tackled this in slightly different ways. See https://github.com/robmorgan/phinx/pull/489

**Comment by dancryer** [comment]
Hi @robmorgan @shadowhand - Is there a reason that this PR and #489 are sitting open without response? I'm really keen to see this functionality merged into Phinx, so if there's a problem with the implementation I'd be more than happy to fix it.

**Comment by DropdeadFredd** [comment]
Hi @robmorgan, @shadowhand 

I would really like to see this functionality in Phinx.

Any chance we can get an update? Is it being considered or is there an issue?  Any response would be very much appreciated.

Thanks

**Comment by antonienko** [comment]
+1 I need this functionality in order to separate schema migrations from data migrations.

**Comment by tomaj** [comment]
:+1: really nice feature, i need this :-)

**Comment by lulco** [comment]
:+1:

**Comment by Tezar** [comment]
:+1: nice, I would also welcome this to be merged. My use case is to support migrations in modular application.

**Comment by dancryer** [comment]
Hi @robmorgan - I've updated my branch to the latest `0.4.x-dev`. Is there any chance this PR could be merged? :pray:

**Comment by robmorgan** [comment]
if a Choice Question is asked, there should be a way to set the 'choice' using command line options or arguments, otherwise Phinx can no longer run non-interactively by a wrapper application/script.

**Comment by robmorgan** [comment]
The Seed command, docs and outstanding bugs are also Pri 1 right now.

**Comment by dancryer** [comment]
Hi @robmorgan - As requested I've added the ability to set the migration path non-interactively in the create command.

**Comment by robmorgan** [comment]
ok thanks

**Comment by aimfeld** [comment]
:+1: This seems to solve #232, hope this can be merged soon.

**Comment by dancryer** [comment]
Hey @robmorgan - Just to let you know I've updated the branch to resolve the conflict introduced when https://github.com/robmorgan/phinx/commit/82e35104dc2d31a39647573bd013fde7fe68d06a was merged.

It'd be great to get this merged if we could, to avoid having to maintain the branches in parallel.

**Comment by markushausammann** [comment]
Great, thanks @dancryer , please merge and tag fast @robmorgan ! We need this very urgently.

**Comment by dancryer** [comment]
Hi @robmorgan - Sorry to chase up on this again, but is there any chance this will be merged soon? 

I'm currently having to use a custom repository in my projects to pull my forked version, and I'd really love to switch back to using the mainline Phinx repository. :+1:

**Comment by aimfeld** [comment]
I ended up copying migration files from several paths into the phinx migration directory during the deployment process.

**Comment by aaronjameslang** [comment]
Pulling in these improvements would be greatly appreciated. They're important for anyone trying to create a modular applcation.

Thanks for all you work @robmorgan @dancryer

**Comment by julianseeger** [comment]
:+1:  need this too.
Btw @robmorgan this Feature would even allow seeds to be maintained in a seperate directory and ge applied from a second dir (making a special seed feature less important)

**Comment by shadowhand** [comment]
Thank you for contributing! The branch you made this PR against is no longer accepting patches. This probably happened because we didn't merge your changes fast enough. :sob:

Please create a new PR against the current default branch if you want to see these changes merged.

I merge this as soon as it is available for 0.5.x. Thank you!

**Comment by fwwarr** [comment]
@shadowhand, it seems a PR against 0.5.x is now ready: #742. Thanks!

**Pull request closed without merging**
