### PR TITLE
Added ability to roll back by date string.

### PR DESCRIPTION
**Pull request by jpohlmann**
I've run into this issue more than once, where I want to roll back my database to my version's release date before I roll the code back.

### CODE REVIEW

**Comment by stoiev** [comment]
+ 1 for this pull request.

**Comment by IngwiePhoenix** [comment]
I second that!

**Comment by w2pc** [comment]
I upvote this.

**Comment by rquadling** [comment]
Can you recheck why some of the input value are now optional?

If I use a ```-t``` parameter, I will be expected to supply a timestamp. Similarly, if I use a ```-d``` parameter, I'm expecting a timestamp.

In neither case is the timestamp optional - as that implies no target.

**Comment by jpohlmann** [comment]
So I considered doing that, and I certainly still can.  But currently when I run phinx migrate without a -t, it updates to the current revision.  When I run phinx rollback without the -t, it rolls back one revision.  So it didn't look like -t was actually required.  I didn't want to mess that up by raising an error.

Having said that, I can add that in if it makes sense.

**Comment by robmorgan** [comment]
I like this and thanks for the tests as well.

**Pull request merged**
