### PR TITLE
Fixing issues found by PHPStan & Integrating PHPStan

### PR DESCRIPTION
**Pull request by ondrejmirtes**
I ran [PHPStan](https://github.com/phpstan/phpstan) on your codebase and it found these issues. Feel free to comment on the fixes. I think it'd also to be beneficial to integrate PHPStan into your Travis build so you can prevent these errors in the future.

You can find out more about [PHPStan on Medium.com](https://medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3).

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
BTW that it [found this problem](https://github.com/robmorgan/phinx/pull/1007/commits/57edd50c650a1835861338e9e8946402a25ced98#diff-fbc83579efcb81b2d5fbd71f250a5cdfR24) is pretty cool I think :)

**Comment by ondrejmirtes** [comment]
I updated the PR with newest PHPStan version 0.6.

**Comment by robmorgan** [comment]
@ondrejmirtes thanks and cool tool. I've read the article, I want to play around with it.

**Comment by robmorgan** [comment]
@ondrejmirtes hey mate really cool tool! happy to integrate!

**Comment by ondrejmirtes** [comment]
@robmorgan I'm happy to hear that! :) If you'd need any help integrating PHPStan on some other project, let me know.

**Comment by rquadling** [comment]
Would it also be feasible to incorporate php-cs-fixer?

By adding suitable entries in composer.json in the `"scripts"` section, other devs can easily run the same tools.

For example: my main work has (amongst others) ...

```json
    "run-sa": "vendor/bin/phpstan analyse --ansi --no-progress -c phpstan.neon -l 4 classes controllers lib",
    "run-fixer": "vendor/bin/php-cs-fixer fix",
    "run-tests": "vendor/bin/phpunit --exclude-group requires-db"
```

So all our devs can easily run `composer run-sa` without really caring about the rest of the params. And we can call the same command in our pipeline.

**Pull request merged**
