### PR TITLE
Adding support for multiple migration paths (merged from dancryer repo)

### PR DESCRIPTION
**Pull request by danives3d**
Saw that the pull request for multiple migration paths had been closed what with the release of 0.5 - so I merged dans work into the 0.5 branch to try and get this pushed through into the main repo :)

### CODE REVIEW

**Comment by Sieg** [comment]
Nice! Hope this will be approved as soon as possible :)

**Comment by shadowhand** [comment]
This branch is out of date with current upstream.

Support was added for multiple paths (via glob braces) in #736. I would like to see both braces and arrays allowed.

**Comment by Sieg** [comment]
I used the feature for a while, and how about the case: I introduced some subsystem for my main system, and registered that submodule migrations path to phinx so these migrations can be used now. Lets say system have 201601 migrations, and module have 201512.. i need to migrate down only module migrations, because module did something bad.. so now i need to rollback all my migrations to access module migrations for rollback and this will destroy a lot of my data..

Maybe it should be possible to rollback by directories too? The same way how its done with migrations creation?

**Comment by bartosz-maciaszek** [comment]
Is this PR going to be merged anytime soon? I'd love to have it as well. Unfortunately, `GLOB_BRACE` is not available in non GNU systems, so not everyone can use it...

It would be great if Phinx supported both braces and arrays.

**Comment by bartosz-maciaszek** [comment]
Since there's no response from the creator, I have created [a separate pull request](https://github.com/robmorgan/phinx/pull/871) based on this one, but branched off from the latest `0.5.x-dev`.

**Comment by robmorgan** [comment]
closing in favor of: https://github.com/robmorgan/phinx/pull/927

**Pull request closed without merging**
