### PR TITLE
No prev migration check on rollback

### PR DESCRIPTION
**Pull request by Ducain**
When a team is working on various branches, a situation can arise where rolling back the most recent migration means the previous migration doesn't exist, because it was executed when another branch was checked out. It seems logical to me that executing a rollback with no target should not fail if the previous migration doesn't exist on the current branch, as no action is being taken on that previous migration.

This change executes the rollback of the most recent migration, without checking for the existence of the previous migration.

### CODE REVIEW

**Comment by temperedvision** [comment]
This change makes sense to me and would go some way to deal with the scenario mentioned in the pull request (developing and testing migrations in isolation against a shared database)

**Comment by RQuadling** [comment]
If you are using branches with each having its own migrations which are isolated from each other until feature finished, when you switch branches without first rolling back the outgoing branch and migrating the incoming branch, your DB will be a bit of a mess.

Unless you have a different pattern of behaviour.

How do you manage that?

**Comment by Ducain** [comment]
@RQuadling As any branch can have multiple migrations (most often the addition of tables and columns), and during development new data added for feature testing, rolling back all migrations for a branch before switching to another would become inefficient very quickly.  Additionally, the existence of tables or table columns doesn't constitute 'a mess' in our minds.  It would be odd for the existence of a table and/or columns to break functionality on another branch. 

I created a new phinx phar with the changes I made here, and we've been using it in development. Definitely an improvement in our workflow.

**Comment by RQuadling** [comment]
@Ducain, ah. OK. Our migrations include views/sp/triggers/etc. Not just an additional column here or there. For our RI, the public interface of our DB for our repo mechanics need to tie up, so the rollback/migrate works well for us. I think using solid state drive has spoiled me rotten.

**Comment by Ducain** [comment]
@RQuadling Makes sense. We use very few views/sp/triggers because we're in MySQL and try to limit the existence of such things. Our migrations are almost completely tables/columns.

**Comment by shadowhand** [comment]
Thank you for contributing! The branch you made this PR against is no longer accepting patches. This probably happened because we didn't merge your changes fast enough. :sob:

Please create a new PR against the current default branch if you want to see these changes merged.

**Pull request closed without merging**
